name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{'44.200.2.219'}}
          username: root
          password: ${{'T@k@hiro203'}}
          port: ${{22}}
          script: |
            cd jpetstore-6
            ./mvnw cargo:run -P tomcat90
